import Image from 'next/image'
import Link from 'next/link'
import CallLink from '@/components/CallLink'
import { pageMetadata } from '@/lib/pageSeo'

export const metadata = pageMetadata('Um Eðalkaup — reynsla af bílainnflutningi', 'Kynntu þér Eðalkaup og þjónustu okkar við leit, kaup og innflutning bíla frá Bandaríkjunum, Kanada og Evrópu til Íslands.', '/um-okkur')

export default function UmOkkurPage() {
  return <div className="pt-16 lg:pt-20">
    <section className="dealer-hero"><div className="dealer-container py-16 sm:py-24 grid lg:grid-cols-[1.4fr_1fr] gap-12 items-center"><div><p className="dealer-eyebrow mb-5">Um Eðalkaup</p><h1 className="text-4xl sm:text-6xl font-semibold tracking-[-.05em] leading-[1.08]">Bílaáhugi.<br />Reynsla.<br /><span className="text-accent-dark dark:text-accent">Persónuleg þjónusta.</span></h1><p className="text-lg text-gray-600 dark:text-slate-300 leading-relaxed max-w-xl mt-7">Í yfir 25 ár höfum við aðstoðað við innflutning bíla til Íslands. Við leitum að bílum í Bandaríkjunum, Kanada og Evrópu og fylgjum ferlinu frá leit til afhendingar.</p></div><div className="border-l border-black/15 dark:border-white/20 pl-8"><p className="text-8xl font-semibold tracking-tighter text-accent-dark dark:text-accent">25+</p><p className="mt-4 text-gray-600 dark:text-slate-300">ára reynsla af bílainnflutningi</p></div></div></section>
    <section className="dealer-container py-16 sm:py-24 grid lg:grid-cols-2 gap-12 lg:gap-20 items-center"><div className="relative aspect-[4/3] rounded-xl overflow-hidden bg-gray-100"><Image src="/images/siggi.jpg" alt="Sigurður Róbertsson, framkvæmdastjóri Eðalkaupa" fill sizes="(max-width: 1023px) 100vw, 50vw" className="object-cover object-top" /></div><div><p className="dealer-eyebrow mb-4">Fólkið á bak við bílana</p><h2 className="dealer-heading">Beint samband.<br />Frá fyrsta degi.</h2><p className="mt-5 text-gray-600 dark:text-slate-300 leading-relaxed">Sigurður Róbertsson er framkvæmdastjóri Eðalkaupa. Hafðu samband til að ræða ákveðinn bíl, fá aðstoð við leit eða fara yfir hvernig innflutningur gæti hentað þér.</p><p className="font-semibold mt-7">Sigurður Róbertsson</p><p className="text-sm text-gray-500 dark:text-slate-400 mt-1">Framkvæmdastjóri Eðalkaupa</p><CallLink placement="about" className="dealer-button mt-7">Hringja í 699 2011 <span aria-hidden="true">↗</span></CallLink></div></section>
    <section className="dealer-stock"><div className="dealer-container py-16"><p className="dealer-eyebrow mb-4">Þjónustan okkar</p><h2 className="dealer-heading mb-10">Við hjálpum þér að velja.</h2><div className="grid md:grid-cols-3 gap-8">{[
      ['Meira úrval', 'Við skoðum möguleika erlendis út frá þínum óskum um gerð, árgerð og búnað.'],
      ['Skýr næstu skref', 'Við förum yfir upplýsingar um bílinn, kostnaðarliði og áætlaða afhendingu áður en gengið er frá kaupum.'],
      ['Aðstoð í gegnum ferlið', 'Leit, kaup, flutningur og tollafgreiðsla. Afhending er skipulögð í samráði við þig.'],
    ].map(([title, description], index) => <div key={title} className="border-t border-black/15 dark:border-white/20 pt-6"><p className="dealer-eyebrow mb-4">0{index + 1}</p><h3 className="text-xl font-semibold mb-3">{title}</h3><p className="text-gray-600 dark:text-slate-300 leading-relaxed">{description}</p></div>)}</div><Link href="/bilainnflutningur" className="inline-block mt-10 font-semibold underline underline-offset-4">Sjá hvernig innflutningur virkar →</Link></div></section>
    <section className="dealer-container py-16 flex flex-col sm:flex-row justify-between gap-8"><div><h2 className="text-xl font-semibold mb-4">Viðskipti við Eðalkaup</h2><p className="text-gray-600 dark:text-slate-300">Öll viðskipti eru við Úranus ehf., kt. 5010963189.</p><p className="text-gray-600 dark:text-slate-300 mt-2">Laugavegur 44, 101 Reykjavík.</p></div><Link href="/hafa-samband" className="dealer-button self-start">Hafa samband <span aria-hidden="true">↗</span></Link></section>
  </div>
}
